const Phaser = require('phaser');
const { POSITIONS: { HOME_MAIN }, TEXT } = require('./constants');

const X = HOME_MAIN.x();
const Y = HOME_MAIN.y();
const WIDTH = HOME_MAIN.width();
const HEIGHT = HOME_MAIN.height();

class HomeRankings extends Phaser.Scene {
    constructor() {
        super({ key: 'HomeRankings' });
    }

    create() {
        this.add.text(X, Y, 'Rankings Scene', TEXT.HEADER);
        this.add.text(X, Y + HEIGHT * 0.1, 'some stuff here', TEXT.NORMAL);
    }

    cleanUp() {
        this.scene.remove();
    }
}

module.exports = HomeRankings;
