const Phaser = require('phaser');
const { POSITIONS: { HOME_MAIN }, TEXT } = require('./constants');

const X = HOME_MAIN.x();
const Y = HOME_MAIN.y();
const WIDTH = HOME_MAIN.width();
const HEIGHT = HOME_MAIN.height();

class HomeShop extends Phaser.Scene {
    constructor() {
        super({ key: 'HomeShop' });
    }

    create() {
        this.add.text(X, Y, 'Shop Scene', TEXT.HEADER);
        this.add.text(X, Y + HEIGHT * 0.1, 'rulul', TEXT.NORMAL);
    }

    cleanUp() {
        this.scene.remove();
    }
}

module.exports = HomeShop;
